### PR TITLE
Read cargo metadata from environment

### PR DESCRIPTION
**Pull request by vladimyr**
This PR removes hardcoded version, author and description strings and replaces them with cargo metadata.

### CODE REVIEW

**Review by dmfutcher — CHANGES_REQUESTED** [review]
Hi @vladimyr.

Would be happy to accept a change to do this, but want to avoid pulling in all this auto-formatting. I'm also slightly concerned about needing `#[allow(deprecated)]` used for the `crate_authors!` macro, is this macro deprecated?

**Comment by vladimyr** [comment]
> but want to avoid pulling in all this auto-formatting

Removed auto-formatting ✅ 

> I'm also slightly concerned about needing `#[allow(deprecated)]` used for the `crate_authors!` macro, is this macro deprecated?

Macro is definitely not deprecated (see https://docs.rs/clap/2.33.3/clap/macro.crate_authors.html) and with the latest `clap` release (see https://github.com/clap-rs/clap/issues/1552) it is also unneeded so I removed it ✅

**Review by dmfutcher — APPROVED** [review]
👍  Looks good to me, will merge!

**Comment by dmfutcher** [comment]
Thanks very much for contributing @vladimyr

**Pull request merged**
